#!/bin/sh

# Copyright 2015-2020 Joel Allen Luellwitz and Emily Frost
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Default Linux user and group information
NETCHECK_USER='netcheck'
NETCHECK_USER_COMMENT='Netcheck Daemon'
NETCHECK_GROUP='netcheck'

case "$1" in
    configure)

    # Add the netcheck group
    if ! getent group "$NETCHECK_GROUP" >> /dev/null; then
        echo -n "Adding group $NETCHECK_GROUP..."
        addgroup --quiet --system "$NETCHECK_GROUP" 2> /dev/null
        echo "done"
    fi

    # Add the netcheck user
    if ! getent passwd "$NETCHECK_USER" >> /dev/null; then
        echo -n "Adding system user $NETCHECK_USER..."
        adduser --quiet --system --ingroup "$NETCHECK_GROUP" --no-create-home --disabled-password \
            "$NETCHECK_USER" 2> /dev/null
        echo "done"
    fi

    # Adjust the user regardless of whether this script created the user or not.
    #   (The user might already exist.)
    usermod -c "$NETCHECK_USER_COMMENT" -d "/nonexistent" -g "$NETCHECK_GROUP" \
        "$NETCHECK_USER"
    ;;
esac

update-rc.d netcheck defaults || exit 1
systemctl restart netcheck || exit 1
